aedenthorn/StardewValleyMods

MobilePhone/MobilePhoneCall.cs
Hi,
I fixed wrong paths for companion recruitment dialogues fetched by your Mobile phone mod.
=> Fixed dialogue paths for NPC Adventures recruitment

Swim/AbigailMetalHead.cs, Swim/ModEntry.cs, Swim/Swim.csproj, Swim/SwimDialog.cs, Swim/SwimHelperEvents.cs, Swim/SwimMaps.cs, Swim/SwimPatches.cs, Swim/SwimUtils.cs, Swim/packages.config
Wrapped shared values in PerScreen<T> and fixed joystick input to fire using the right thumb stick.
=> A fix for split screem multiplayer

AFKTimePause/ModEntry.cs, AFKTimePause/i18n/default.json, AFKTimePause/i18n/fr.json
* Added translation for GMCM
* Added a tooltip for the "Freeze Game" option
=> [AFKTimePause] Add translation support and French translation

AdditionalMineMaps/ModEntry.cs, AdditionalMineMaps/i18n/default.json, AdditionalMineMaps/i18n/fr.json
* Added translation support for the GMCM menu
=> [AdditionalMineMaps] Add translation support and French translation

AdvancedCooking/ModEntry.cs, AdvancedCooking/i18n/default.json, AdvancedCooking/i18n/fr.json
* Added translation support for the GMCM menu
* Used localized name of recipes
=> [AdvancedCooking] Improve translation support and add French translation

AdvancedDrumBlocks/ModEntry.cs, AdvancedDrumBlocks/i18n/default.json, AdvancedDrumBlocks/i18n/fr.json
* Added translation support for the GMCM menu
=> [AdvancedDrumBlocks] Add translation support and French translation

AdvancedFluteBlocks/ModEntry.cs, AdvancedFluteBlocks/i18n/default.json, AdvancedFluteBlocks/i18n/fr.json
* Added translation support for the GMCM menu
=> [AdvancedFluteBlocks] Add translation support and French translation

AutoPetterTweaks/ModEntry.cs, AutoPetterTweaks/i18n/default.json, AutoPetterTweaks/i18n/fr.json
* (428c341cd861dbaad27aa59573e806269dcbf794) Added translation support for the GMCM menu
* (a6cdf8228509e3e4e9abd470777e71a8720c7561) Added French translation
=> [AutoPetterTweaks] Add translation support and French translation

BirthdayBuff/i18n/fr.json
* (c64186b202879a1967a6f751e289dbc7abe069c7) Added French translation
=> [BirthdayBuff] Add French translation

BuffFramework/i18n/default.json, BuffFramework/i18n/fr.json
* (d67b1917563f70468e70f63d2dd726d27bf254bf) The unused `mail` key has been removed from the translation file.
* (2a1041761a81aed281005e36198986ed5ed489b8) French translation has been added.
=> [BuffFramework] Add French translation

BirthdayFriendship/i18n/fr.json
* (82c93d8d51ec6584d6723e9cf47e742f00aa7b84) Added French translation
=> [BirthdayFriendship] Add French translation

BulkAnimalPurchase/ModEntry.cs, BulkAnimalPurchase/i18n/default.json, BulkAnimalPurchase/i18n/fr.json
* (f379bee8fc731c6acfbee408527a4a2303155302) Added translation support for the GMCM menu.
* (aa056f4c11df911c5dfaa4108e5aae5597750629) Added French translation.
=> [BulkAnimalPurchase] Improve translation support and add French translation

CatalogueFilter/ModEntry.cs, CatalogueFilter/i18n/default.json, CatalogueFilter/i18n/fr.json
* (a557ba8359a94085d63637569b8ab13481e53730) The `GameLoop_GameLaunched` function is not used. `GameLoop_GameLaunched` function has been subscribed to the `helper.Events.GameLoop.GameLaunched` event.
* (3e1849015ee21a793dd4dd89b68bd92add96edba) Added translation support for the GMCM menu.
* (c6c1552cff730d32220835746c65f6c6d298d5db) Added French translation.
*Note: UpdateKeys is missing in the manifest.*
=> [CatalogueFilter] Fix unused GameLoop_GameLaunched function, improve translation support and add French Translation

ConnectedGardenPots/ModEntry.cs, ConnectedGardenPots/i18n/default.json, ConnectedGardenPots/i18n/fr.json
* (953e42f5347e5a0da10ca94ce91abe3989bb194a) Added translation support for the GMCM menu.
* (ff8f70882b5ae96d3fcb1407ca52c1043be0f65f) Added French translation.
=> [ConnectedGardenPots] Add translation support and French translation

CooperativeEggHunt/ModEntry.cs, CooperativeEggHunt/i18n/default.json, CooperativeEggHunt/i18n/fr.json
* (23d0839ea0f9b8fbb753a6e8b02f1efeeb2735ce) Added translation support for the GMCM menu.
* (55041aa36573d3845f20c30a13cd96941e6bc419) Added French translation.
=> [CooperativeEggHunt] Improve translation support and add French translation

CraftFromContainers/ModEntry.cs, CraftFromContainers/i18n/default.json, CraftFromContainers/i18n/fr.json
* (ae4e62bf91c955a40f139e52b0d8e69db4073172) Added translation support for the GMCM menu.
* (289f556cd47b67d82276335b9f65257d0b491340) Added French translation.
=> [CraftFromContainers] Add translation support and French translation

CropHarvestBubbles/i18n/fr.json
* (08720c980135e774890a4888b8a8c3a96b0e3ffe) Added French translation.
=> [CropHarvestBubbles] Add French translation

CropHat/CodePatches.cs, CropHat/ModEntry.cs, CropHat/i18n/default.json, CropHat/i18n/fr.json
* (3c9411d709f87909c7435593ca1567d673af3581) Added translation support for the GMCM menu and used localized crop names.
* (7adb20b4f016d98fcc6f8df27a6e26ae2ac7e0d7) Added French translation.
=> [CropHat] Improve translation support and add French translation

CropMarkers/i18n/default.json, CropMarkers/i18n/fr.json
* (8505f41eccf3b4ec86d0ec1cd03541d92762de55) Deleted the unused `GMCM_Option_IgnoreFlowers_Name` key.
* (9b10ff2b933f0c1a3d50a2256e23056dd628cc22) Added French translation.
=> [CropMarkers] Add French translation

CropVariation/ModEntry.cs, CropVariation/i18n/default.json, CropVariation/i18n/fr.json
* (de5480b8a3391052160e8cae51b85e1aef40c0db) Added translation support for the GMCM menu.
* (fef29879c6cf646c767f9152e18e02d22b36ce2f) Added French translation.
=> [CropVariation] Add translation support and French translation

CropsSurviveSeasonChange/i18n/fr.json
* (382f305151f423eda1b7c50581cacc391e938c0e) Added French translation.
=> [CropsSurviveSeasonChange] Add French translation

CustomGiftLimits/ModEntry.cs, CustomGiftLimits/i18n/default.json, CustomGiftLimits/i18n/fr.json
* (8593a816ba73f29694c01bea253b7944ded8dfe9) Added translation support for the GMCM menu.
* (199c2aaec5a633cd8c45f010c0b717d4510c92ed) Added French translation.
=> [CustomGiftLimits] Add translation support and French translation

CustomHay/IGenericModConfigMenuApi.cs, CustomHay/ModEntry.cs, CustomHay/i18n/default.json, CustomHay/i18n/fr.json
* (590a14ca8ee6a748ea15dbc17daa49a559d93ec6) Improved GMCM menu and added translation support for the GMCM menu:
* Replaced **TextOption** with **NumberOption** for floating numbers.
* Added translation support.
* (723c2a3c7a6c5066c8f518d65a851b4d004f6c3b) Added French translation.
=> [CustomHay] Improve GMCM menu, add translation support and French translation

AdvancedFluteBlocks/AdvancedFluteBlocks.csproj, AdvancedFluteBlocks/AdvancedFluteBlocksApi.cs, AdvancedFluteBlocks/CodePatches.cs, AdvancedFluteBlocks/IAdvancedFluteBlocksApi.cs, AdvancedFluteBlocks/IGenericModConfigMenuApi.cs, AdvancedFluteBlocks/ModConfig.cs, AdvancedFluteBlocks/ModEntry.cs, AdvancedFluteBlocks/i18n/default.json, AdvancedFluteBlocks/i18n/fr.json, AdvancedFluteBlocks/i18n/ru.json, AdvancedFluteBlocks/manifest.json
See: [Release notes](https://github.com/mouahrara/aedenthorn/blob/master/AdvancedFluteBlocks/release-notes.md)
=> [Advanced Flute Blocks] Update to 0.2.1 (based on 0.2.1-unofficial.3-mouahrara)

PartialHearts/CodePatches.cs, PartialHearts/IGenericModConfigMenuApi.cs, PartialHearts/ModConfig.cs, PartialHearts/ModEntry.cs, PartialHearts/PartialHearts.csproj, PartialHearts/i18n/default.json, PartialHearts/i18n/fr.json, PartialHearts/manifest.json
See: [Release notes](https://github.com/mouahrara/aedenthorn/blob/master/PartialHearts/release-notes.md)
=> [Partial Hearts] Update to 0.2.2 (based on 0.2.2-unofficial.1-mouahrara)

NightEventChanceTweak/CodePatches.cs, NightEventChanceTweak/IGenericModConfigMenuApi.cs, NightEventChanceTweak/ModConfig.cs, NightEventChanceTweak/ModEntry.cs, NightEventChanceTweak/NightEventChanceTweak.csproj, NightEventChanceTweak/i18n/default.json, NightEventChanceTweak/i18n/fr.json, NightEventChanceTweak/manifest.json
See: [Release notes](https://github.com/mouahrara/aedenthorn/blob/master/NightEventChanceTweak/release-notes.md)
=> [Night Event Chance Tweak] Update to 0.1.1 (based on 0.1.1-unofficial.1-mouahrara)

LikeADuckToWater/CodePatches.cs, LikeADuckToWater/HopInfo.cs, LikeADuckToWater/IGenericModConfigMenuApi.cs, LikeADuckToWater/LikeADuckToWater.csproj, LikeADuckToWater/Methods.cs, LikeADuckToWater/ModConfig.cs, LikeADuckToWater/ModEntry.cs, LikeADuckToWater/i18n/default.json, LikeADuckToWater/i18n/fr.json, LikeADuckToWater/manifest.json
See: [Release notes](https://github.com/mouahrara/aedenthorn/blob/master/LikeADuckToWater/release-notes.md)
=> [Like a Duck to Water] Update to 0.4.5 (based on 0.4.5-unofficial.1-mouahrara)

WateringCanTweaks/CodePatches.cs, WateringCanTweaks/Compatibility.cs, WateringCanTweaks/IGenericModConfigMenuApi.cs, WateringCanTweaks/ModConfig.cs, WateringCanTweaks/ModEntry.cs, WateringCanTweaks/WateringCanTweaks.csproj, WateringCanTweaks/i18n/default.json, WateringCanTweaks/i18n/fr.json, WateringCanTweaks/manifest.json
See: [Release notes](https://github.com/mouahrara/aedenthorn/blob/master/WateringCanTweaks/release-notes.md)
=> [Watering Can Tweaks] Update to 0.3.2 (based on 0.3.2-unofficial.1-mouahrara)

OmniTools/CodePatches.cs, OmniTools/Methods.cs, OmniTools/OmniTools.csproj, OmniTools/ToolInfo.cs, OmniTools/manifest.json
Mostly minor; bit of a messy patch for `ToolDescription`.
=> [OmniTools] Update for Stardew 1.6 / SMAPI 4.0.

FloatingGardenPots/CodePatches.cs, FloatingGardenPots/FloatingGardenPots.csproj, FloatingGardenPots/IGenericModConfigMenuApi.cs, FloatingGardenPots/Methods.cs, FloatingGardenPots/ModConfig.cs, FloatingGardenPots/ModEntry.cs, FloatingGardenPots/i18n/default.json, FloatingGardenPots/i18n/fr.json, FloatingGardenPots/manifest.json
See: [Release notes](https://github.com/mouahrara/aedenthorn/blob/master/FloatingGardenPots/release-notes.md)
=> [Floating Garden Pots] Update to 0.1.1 (based on 0.1.1-unofficial.2-mouahrara)

GenieLamp/CodePatches.cs, GenieLamp/GenieLamp.csproj, GenieLamp/IGenericModConfigMenuApi.cs, GenieLamp/Methods.cs, GenieLamp/ModConfig.cs, GenieLamp/ModEntry.cs, GenieLamp/ObjectPickMenu.cs, GenieLamp/i18n/default.json, GenieLamp/i18n/fr.json, GenieLamp/manifest.json
See: [Release notes](https://github.com/mouahrara/aedenthorn/blob/master/GenieLamp/release-notes.md)
=> [Genie Lamp] Update to 0.1.2 (based on 0.1.2-unofficial.1-mouahrara)

DynamicMapTiles/CodePatches.cs, DynamicMapTiles/DynamicMapTiles.csproj, DynamicMapTiles/DynamicMapTilesApi.cs, DynamicMapTiles/DynamicTileInfo.cs, DynamicMapTiles/IAdvancedLootFrameworkApi.cs, DynamicMapTiles/IGenericModConfigMenuApi.cs, DynamicMapTiles/Methods.cs, DynamicMapTiles/ModConfig.cs, DynamicMapTiles/ModEntry.cs, DynamicMapTiles/PushedTile.cs, DynamicMapTiles/TweakData.cs, DynamicMapTiles/i18n/default.json, DynamicMapTiles/i18n/fr.json, DynamicMapTiles/manifest.json
See: [Release notes](https://github.com/mouahrara/aedenthorn/blob/master/DynamicMapTiles/release-notes.md)
=> [Dynamic Map Tiles] Update to 0.9.7 (based on 0.9.7-unofficial.1-mouahrara)

FishSpotBait/CodePatches.cs, FishSpotBait/FishSpotBait.csproj, FishSpotBait/IGenericModConfigMenuApi.cs, FishSpotBait/Methods.cs, FishSpotBait/ModConfig.cs, FishSpotBait/ModEntry.cs, FishSpotBait/i18n/default.json, FishSpotBait/i18n/fr.json, FishSpotBait/manifest.json
See: [Release notes](https://github.com/mouahrara/aedenthorn/blob/master/FishSpotBait/release-notes.md)
=> [Fish Spot Bait] Update to 0.1.2 (based on 0.1.2-unofficial.1-mouahrara)

CustomStarterFurniture/CodePatches.cs, CustomStarterFurniture/CustomStarterFurniture.csproj, CustomStarterFurniture/IGenericModConfigMenuApi.cs, CustomStarterFurniture/Methods.cs, CustomStarterFurniture/ModConfig.cs, CustomStarterFurniture/ModEntry.cs, CustomStarterFurniture/StarterItemData.cs, CustomStarterFurniture/i18n/default.json, CustomStarterFurniture/i18n/fr.json, CustomStarterFurniture/manifest.json
See: [Release notes](https://github.com/mouahrara/aedenthorn/blob/master/CustomStarterFurniture/release-notes.md)
=> [Custom Starter Furniture] Update to 0.1.1 (based on 0.1.1-unofficial.1-mouahrara)

CropsSurviveSeasonChange/CodePatches.cs, CropsSurviveSeasonChange/CropsSurviveSeasonChange.csproj, CropsSurviveSeasonChange/IGenericModConfigMenuApi.cs, CropsSurviveSeasonChange/Methods.cs, CropsSurviveSeasonChange/ModConfig.cs, CropsSurviveSeasonChange/ModEntry.cs, CropsSurviveSeasonChange/i18n/default.json, CropsSurviveSeasonChange/i18n/fr.json, CropsSurviveSeasonChange/manifest.json
See: [Release notes](https://github.com/mouahrara/aedenthorn/blob/master/CropsSurviveSeasonChange/release-notes.md)
=> [Crops Survive Season Change] Update to 0.1.3 (based on 0.1.3-unofficial.3-mouahrara)

CropWateringBubbles/CodePatches.cs, CropWateringBubbles/CropWateringBubbles.csproj, CropWateringBubbles/IGenericModConfigMenuApi.cs, CropWateringBubbles/Methods.cs, CropWateringBubbles/ModConfig.cs, CropWateringBubbles/ModEntry.cs, CropWateringBubbles/i18n/default.json, CropWateringBubbles/i18n/fr.json, CropWateringBubbles/i18n/ko.json, CropWateringBubbles/manifest.json
See: [Release notes](https://github.com/mouahrara/aedenthorn/blob/master/CropWateringBubbles/release-notes.md)
=> [Crop Watering Bubbles] Update to 0.2.5 (based on 0.2.5-unofficial.1-mouahrara)

CropMarkers/CodePatches.cs, CropMarkers/CropMarkers.csproj, CropMarkers/IGenericModConfigMenuApi.cs, CropMarkers/Methods.cs, CropMarkers/ModConfig.cs, CropMarkers/ModEntry.cs, CropMarkers/i18n/default.json, CropMarkers/i18n/fr.json, CropMarkers/manifest.json
See: [Release notes](https://github.com/mouahrara/aedenthorn/blob/master/CropMarkers/release-notes.md)
=> [Crop Markers] Update to 0.2.1 (based on 0.2.1-unofficial.2-mouahrara)

CustomSpouseRooms/CustomSpouseRooms.csproj, CustomSpouseRooms/LocationPatches.cs, CustomSpouseRooms/Methods.cs, CustomSpouseRooms/manifest.json
Please review - there were a couple changes made that I'm just not 100% confident in, but I've done my best to get it right. Meanwhile, it does build and run without crashing on startup.
=> Updated CustomSpouseRooms for 1.6

CustomFixedDialogue/CustomFixedDialogue.csproj, CustomFixedDialogue/DialoguePatches.cs, CustomFixedDialogue/ModEntry.cs, CustomFixedDialogue/manifest.json
- I could not figure out how to fix the Harmony Patch for Dialogue.convertToDwarvish - I'm really sorry.
Otherwise, these changes compile and run, and they look correct to me
Found some unreachable code - is this intentional?
=> CustomFixedDialogue PARTIAL updates for 1.6

CustomSpousePatioRedux/CodePatches.cs, CustomSpousePatioRedux/CustomSpousePatioRedux.csproj, CustomSpousePatioRedux/HelperMethods.cs, CustomSpousePatioRedux/ModEntry.cs, CustomSpousePatioRedux/manifest.json
=> [CustomSpousePatioRedux] Update to 1.6

ConnectedGardenPots/CodePatches.cs, ConnectedGardenPots/ConnectedGardenPots.csproj, ConnectedGardenPots/IGenericModConfigMenuApi.cs, ConnectedGardenPots/ModConfig.cs, ConnectedGardenPots/ModEntry.cs, ConnectedGardenPots/i18n/default.json, ConnectedGardenPots/i18n/fr.json, ConnectedGardenPots/manifest.json
See: [Release notes](https://github.com/mouahrara/aedenthorn/blob/master/ConnectedGardenPots/release-notes.md)
=> [Connected Garden Pots] Update to 0.1.1 (based on 0.1.1-unofficial.2-mouahrara)

BetterElevator/BetterElevator.csproj, BetterElevator/BetterElevatorMenu.cs, BetterElevator/CodePatches.cs, BetterElevator/IGenericModConfigMenuApi.cs, BetterElevator/ModConfig.cs, BetterElevator/ModEntry.cs, BetterElevator/i18n/default.json, BetterElevator/i18n/fr.json, BetterElevator/i18n/ru.json, BetterElevator/manifest.json
See: [Release notes](https://github.com/mouahrara/aedenthorn/blob/master/BetterElevator/release-notes.md)
=> [Better Elevator] Update to 0.2.5 (based on 0.2.5-unofficial.2-mouahrara)
